api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Api/Order/Resource'
  graphql:
    enabled: true
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
    html: ['text/html']
