framework:
  messenger:
    default_bus: messenger.bus.commands
    buses:
      messenger.bus.commands: ~
      messenger.bus.events: ~
    transports:
      async: 'in-memory://'
    routing:
      'OrderComponent\\Messenger\\Message\\OutboxDispatchedMessage': async
