framework:
  messenger:
    failure_transport: failed
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'
      failed: '%env(MESSENGER_FAILURE_TRANSPORT_DSN)%'
    routing:
      'OrderComponent\Message\OrderEventMessage': async
