# syntax=docker/dockerfile:1
FROM php:8.3-fpm AS base

RUN apt-get update && apt-get install -y     git unzip libzip-dev librabbitmq-dev libicu-dev libonig-dev libpq-dev     && docker-php-ext-install intl pdo pdo_pgsql     && pecl install amqp     && docker-php-ext-enable amqp     && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# -- Build stage (vendors)
FROM base AS build
COPY composer.json /var/www/html/
RUN composer install --no-dev --no-interaction --no-progress --prefer-dist --no-scripts || true
COPY . /var/www/html
RUN composer dump-autoload --optimize

# -- Runtime stage
FROM base AS runtime
ENV APP_ENV=prod APP_DEBUG=0
WORKDIR /var/www/html
COPY --from=build /var/www/html /var/www/html

# Opcache recommended settings
RUN docker-php-ext-install opcache
COPY docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

# Permissions for cache/logs
RUN mkdir -p var/cache var/log && chown -R www-data:www-data var

CMD ["php-fpm", "-F"]
