environments:
  staging:
    values: [ charts/ordercomponent/values-staging.yaml ]
  production:
    values: [ charts/ordercomponent/values-production.yaml ]

releases:
  - name: ordercomponent-staging
    namespace: order-staging
    chart: ./charts/ordercomponent
    values:
      - charts/ordercomponent/values.yaml
      - {{ .Environment.Values | toYaml | nindent 6 }}

  - name: ordercomponent-prod
    namespace: order-prod
    installed: {{ eq .Environment.Name "production" | toYaml }}
    chart: ./charts/ordercomponent
    values:
      - charts/ordercomponent/values.yaml
      - charts/ordercomponent/values-production.yaml
