apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-component
spec:
  replicas: 1
  selector:
    matchLabels: { app: order-component }
  template:
    metadata:
      labels: { app: order-component }
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
