apiVersion: v1
kind: Service
metadata:
  name: order-component
spec:
  type: {{ .Values.service.type }}
  selector:
    app: order-component
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
