framework:
  workflows:
    order:
      type: 'state_machine'
      supports:
        - OrderComponent\Entity\Order\Order
      initial_marking: draft
      places:
        - draft
        - placed
        - partially_paid
        - paid
        - partially_shipped
        - shipped
        - partially_refunded
        - refunded
        - completed
      transitions:
        place: { from: draft, to: placed }
        partial_pay: { from: [placed], to: partially_paid }
        pay: { from: [placed, partially_paid], to: paid }
        partial_ship: { from: [paid], to: partially_shipped }
        ship: { from: [paid, partially_shipped], to: shipped }
        partial_refund: { from: [paid, shipped], to: partially_refunded }
        refund: { from: [paid, partially_refunded, shipped], to: refunded }
        complete: { from: [shipped], to: completed }
