releases:
  - name: order-staging
    namespace: order-staging
    chart: ./charts/ordercomponent
    values:
      - ./charts/ordercomponent/values.yaml
  - name: order-prod
    namespace: order-prod
    installed: false
    chart: ./charts/ordercomponent
    values:
      - ./charts/ordercomponent/values.yaml
