version: '3.8'
services:
  nginx:
    image: nginx:1.27-alpine
    ports: ["8080:80"]
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    env_file:
      - ../.env.prod.example
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    volumes:
      - ..:/var/www/html
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: orderdb
      POSTGRES_USER: order
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 6
