apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: order-restricted
allowPrivilegeEscalation: false
readOnlyRootFilesystem: true
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 1000
seLinuxContext:
  type: MustRunAs
users:
  - system:serviceaccount:order-staging:default
  - system:serviceaccount:order-prod:default
