site_name: Project Documentation
nav:
  - Home: index.md
  - Entities:
    - Zone: entities/Zone.md
    - VendorShipment: entities/VendorShipment.md
    - VendorSecurity: entities/VendorSecurity.md
    - VendorRememberMeToken: entities/VendorRememberMeToken.md
    - VendorProfileCover: entities/VendorProfileCover.md
    - VendorProfileAvatar: entities/VendorProfileAvatar.md
    - VendorProfile: entities/VendorProfile.md
    - VendorPayment: entities/VendorPayment.md
    - VendorMessage: entities/VendorMessage.md
    - VendorMediaAttachment: entities/VendorMediaAttachment.md
    - VendorMedia: entities/VendorMedia.md
    - VendorIban: entities/VendorIban.md
    - VendorGroup: entities/VendorGroup.md
    - VendorFavourite: entities/VendorFavourite.md
    - VendorEnGb: entities/VendorEnGb.md
    - VendorDocumentAttachment: entities/VendorDocumentAttachment.md
    - VendorDocument: entities/VendorDocument.md
    - VendorCustomerOrder: entities/VendorCustomerOrder.md
    - VendorConversation: entities/VendorConversation.md
    - VendorCodeStorage: entities/VendorCodeStorage.md
    - VendorChannel: entities/VendorChannel.md
    - VendorCategory: entities/VendorCategory.md
    - VendorAddress: entities/VendorAddress.md
    - Vendor: entities/Vendor.md
    - UserVerificationToken: entities/UserVerificationToken.md
    - TranslatebleTrait: entities/TranslatebleTrait.md
    - TimestampableTrait: entities/TimestampableTrait.md
    - SoftDeletableTrait: entities/SoftDeletableTrait.md
    - TotpAuthenticationTrait: entities/TotpAuthenticationTrait.md
    - RootEntity: entities/RootEntity.md
    - RolePermission: entities/RolePermission.md
    - Role: entities/Role.md
    - PermissionChangeLog: entities/PermissionChangeLog.md
    - ProjectLanguageTrait: entities/ProjectLanguageTrait.md
    - ProductLanguageTrait: entities/ProductLanguageTrait.md
    - ProductType: entities/ProductType.md
    - ProductTag: entities/ProductTag.md
    - ProductStorage: entities/ProductStorage.md
    - ProductShipment: entities/ProductShipment.md
    - ProductReview: entities/ProductReview.md
    - ProductProperty: entities/ProductProperty.md
    - ProductPrice: entities/ProductPrice.md
    - ProductPayment: entities/ProductPayment.md
    - ProductOption: entities/ProductOption.md
    - ProductFavourite: entities/ProductFavourite.md
    - ProductEnGb: entities/ProductEnGb.md
    - ProductCategory: entities/ProductCategory.md
    - ProductAttribute: entities/ProductAttribute.md
    - ProductAttachment: entities/ProductAttachment.md
    - Product: entities/Product.md
    - PaymentToken: entities/PaymentToken.md
    - PaymentMethod: entities/PaymentMethod.md
    - PaymentGateway: entities/PaymentGateway.md
    - PaymentEnUs: entities/PaymentEnUs.md
    - Payment: entities/Payment.md
    - OrderStorage: entities/OrderStorage.md
    - OrderStatusHistory: entities/OrderStatusHistory.md
    - OrderStatus: entities/OrderStatus.md
    - OrderShipmentEnUs: entities/OrderShipmentEnUs.md
    - OrderShipment: entities/OrderShipment.md
    - OrderPaymentEnUs: entities/OrderPaymentEnUs.md
    - OrderPayment: entities/OrderPayment.md
    - OrderLog: entities/OrderLog.md
    - OrderItem: entities/OrderItem.md
    - OrderDiscount: entities/OrderDiscount.md
    - OrderBilling: entities/OrderBilling.md
    - OAuthTrait: entities/OAuthTrait.md
    - ModuleMenu: entities/ModuleMenu.md
    - Module: entities/Module.md
    - MetaTrait: entities/MetaTrait.md
    - MenuItem: entities/MenuItem.md
    - LocaleEn: entities/LocaleEn.md
    - Locale: entities/Locale.md
    - IdempotencyKeyEntity: entities/IdempotencyKeyEntity.md
    - EventMember: entities/EventMember.md
    - EventCategory: entities/EventCategory.md
    - Event: entities/Event.md
    - EntityAssociationHydrator: entities/EntityAssociationHydrator.md
    - Coupon: entities/Coupon.md
    - AddressZipcode: entities/AddressZipcode.md
    - AddressStreetLine: entities/AddressStreetLine.md
    - AddressStreet: entities/AddressStreet.md
    - AddressProvince: entities/AddressProvince.md
    - AddressCountry: entities/AddressCountry.md
    - AddressCode: entities/AddressCode.md
    - AddressCity: entities/AddressCity.md
    - Address: entities/Address.md
  - Factories:
    - ZoneFactory: factories/ZoneFactory.md
    - VendorShipmentFactory: factories/VendorShipmentFactory.md
    - VendorSecurityFactory: factories/VendorSecurityFactory.md
    - VendorRememberMeTokenFactory: factories/VendorRememberMeTokenFactory.md
    - VendorProfileCoverFactory: factories/VendorProfileCoverFactory.md
    - VendorProfileAvatarFactory: factories/VendorProfileAvatarFactory.md
    - VendorProfileFactory: factories/VendorProfileFactory.md
    - VendorPaymentFactory: factories/VendorPaymentFactory.md
    - VendorMessageFactory: factories/VendorMessageFactory.md
    - VendorMediaAttachmentFactory: factories/VendorMediaAttachmentFactory.md
    - VendorMediaFactory: factories/VendorMediaFactory.md
    - VendorIbanFactory: factories/VendorIbanFactory.md
    - VendorGroupFactory: factories/VendorGroupFactory.md
    - VendorFavouriteFactory: factories/VendorFavouriteFactory.md
    - VendorEnGbFactory: factories/VendorEnGbFactory.md
    - VendorDocumentAttachmentFactory: factories/VendorDocumentAttachmentFactory.md
    - VendorDocumentFactory: factories/VendorDocumentFactory.md
    - VendorCustomerOrderFactory: factories/VendorCustomerOrderFactory.md
    - VendorConversationFactory: factories/VendorConversationFactory.md
    - VendorCodeStorageFactory: factories/VendorCodeStorageFactory.md
    - VendorChannelFactory: factories/VendorChannelFactory.md
    - VendorCategoryFactory: factories/VendorCategoryFactory.md
    - VendorAddressFactory: factories/VendorAddressFactory.md
    - VendorFactory: factories/VendorFactory.md
    - UserVerificationTokenFactory: factories/UserVerificationTokenFactory.md
    - TranslatebleTraitFactory: factories/TranslatebleTraitFactory.md
    - TimestampableTraitFactory: factories/TimestampableTraitFactory.md
    - SoftDeletableTraitFactory: factories/SoftDeletableTraitFactory.md
    - TotpAuthenticationTraitFactory: factories/TotpAuthenticationTraitFactory.md
    - RootEntityFactory: factories/RootEntityFactory.md
    - RolePermissionFactory: factories/RolePermissionFactory.md
    - RoleFactory: factories/RoleFactory.md
    - PermissionChangeLogFactory: factories/PermissionChangeLogFactory.md
    - ProjectLanguageTraitFactory: factories/ProjectLanguageTraitFactory.md
    - ProductLanguageTraitFactory: factories/ProductLanguageTraitFactory.md
    - ProductTypeFactory: factories/ProductTypeFactory.md
    - ProductTagFactory: factories/ProductTagFactory.md
    - ProductStorageFactory: factories/ProductStorageFactory.md
    - ProductShipmentFactory: factories/ProductShipmentFactory.md
    - ProductReviewFactory: factories/ProductReviewFactory.md
    - ProductPropertyFactory: factories/ProductPropertyFactory.md
    - ProductPriceFactory: factories/ProductPriceFactory.md
    - ProductPaymentFactory: factories/ProductPaymentFactory.md
    - ProductOptionFactory: factories/ProductOptionFactory.md
    - ProductFavouriteFactory: factories/ProductFavouriteFactory.md
    - ProductEnGbFactory: factories/ProductEnGbFactory.md
    - ProductCategoryFactory: factories/ProductCategoryFactory.md
    - ProductAttributeFactory: factories/ProductAttributeFactory.md
    - ProductAttachmentFactory: factories/ProductAttachmentFactory.md
    - ProductFactory: factories/ProductFactory.md
    - PaymentTokenFactory: factories/PaymentTokenFactory.md
    - PaymentMethodFactory: factories/PaymentMethodFactory.md
    - PaymentGatewayFactory: factories/PaymentGatewayFactory.md
    - PaymentEnUsFactory: factories/PaymentEnUsFactory.md
    - PaymentFactory: factories/PaymentFactory.md
    - OrderStorageFactory: factories/OrderStorageFactory.md
    - OrderStatusHistoryFactory: factories/OrderStatusHistoryFactory.md
    - OrderStatusFactory: factories/OrderStatusFactory.md
    - OrderShipmentEnUsFactory: factories/OrderShipmentEnUsFactory.md
    - OrderShipmentFactory: factories/OrderShipmentFactory.md
    - OrderPaymentEnUsFactory: factories/OrderPaymentEnUsFactory.md
    - OrderPaymentFactory: factories/OrderPaymentFactory.md
    - OrderLogFactory: factories/OrderLogFactory.md
    - OrderItemFactory: factories/OrderItemFactory.md
    - OrderDiscountFactory: factories/OrderDiscountFactory.md
    - OrderBillingFactory: factories/OrderBillingFactory.md
    - OAuthTraitFactory: factories/OAuthTraitFactory.md
    - ModuleMenuFactory: factories/ModuleMenuFactory.md
    - ModuleFactory: factories/ModuleFactory.md
    - MetaTraitFactory: factories/MetaTraitFactory.md
    - MenuItemFactory: factories/MenuItemFactory.md
    - LocaleEnFactory: factories/LocaleEnFactory.md
    - LocaleFactory: factories/LocaleFactory.md
    - IdempotencyKeyEntityFactory: factories/IdempotencyKeyEntityFactory.md
    - EventMemberFactory: factories/EventMemberFactory.md
    - EventCategoryFactory: factories/EventCategoryFactory.md
    - EventFactory: factories/EventFactory.md
    - EntityAssociationHydratorFactory: factories/EntityAssociationHydratorFactory.md
    - CouponFactory: factories/CouponFactory.md
    - AddressZipcodeFactory: factories/AddressZipcodeFactory.md
    - AddressStreetLineFactory: factories/AddressStreetLineFactory.md
    - AddressStreetFactory: factories/AddressStreetFactory.md
    - AddressProvinceFactory: factories/AddressProvinceFactory.md
    - AddressCountryFactory: factories/AddressCountryFactory.md
    - AddressCodeFactory: factories/AddressCodeFactory.md
    - AddressCityFactory: factories/AddressCityFactory.md
    - AddressFactory: factories/AddressFactory.md
  - Tests:
    - ZoneTests: tests/ZoneTests.md
    - VendorShipmentTests: tests/VendorShipmentTests.md
    - VendorSecurityTests: tests/VendorSecurityTests.md
    - VendorRememberMeTokenTests: tests/VendorRememberMeTokenTests.md
    - VendorProfileCoverTests: tests/VendorProfileCoverTests.md
    - VendorProfileAvatarTests: tests/VendorProfileAvatarTests.md
    - VendorProfileTests: tests/VendorProfileTests.md
    - VendorPaymentTests: tests/VendorPaymentTests.md
    - VendorMessageTests: tests/VendorMessageTests.md
    - VendorMediaAttachmentTests: tests/VendorMediaAttachmentTests.md
    - VendorMediaTests: tests/VendorMediaTests.md
    - VendorIbanTests: tests/VendorIbanTests.md
    - VendorGroupTests: tests/VendorGroupTests.md
    - VendorFavouriteTests: tests/VendorFavouriteTests.md
    - VendorEnGbTests: tests/VendorEnGbTests.md
    - VendorDocumentAttachmentTests: tests/VendorDocumentAttachmentTests.md
    - VendorDocumentTests: tests/VendorDocumentTests.md
    - VendorCustomerOrderTests: tests/VendorCustomerOrderTests.md
    - VendorConversationTests: tests/VendorConversationTests.md
    - VendorCodeStorageTests: tests/VendorCodeStorageTests.md
    - VendorChannelTests: tests/VendorChannelTests.md
    - VendorCategoryTests: tests/VendorCategoryTests.md
    - VendorAddressTests: tests/VendorAddressTests.md
    - VendorTests: tests/VendorTests.md
    - UserVerificationTokenTests: tests/UserVerificationTokenTests.md
    - TranslatebleTraitTests: tests/TranslatebleTraitTests.md
    - TimestampableTraitTests: tests/TimestampableTraitTests.md
    - SoftDeletableTraitTests: tests/SoftDeletableTraitTests.md
    - TotpAuthenticationTraitTests: tests/TotpAuthenticationTraitTests.md
    - RootEntityTests: tests/RootEntityTests.md
    - RolePermissionTests: tests/RolePermissionTests.md
    - RoleTests: tests/RoleTests.md
    - PermissionChangeLogTests: tests/PermissionChangeLogTests.md
    - ProjectLanguageTraitTests: tests/ProjectLanguageTraitTests.md
    - ProductLanguageTraitTests: tests/ProductLanguageTraitTests.md
    - ProductTypeTests: tests/ProductTypeTests.md
    - ProductTagTests: tests/ProductTagTests.md
    - ProductStorageTests: tests/ProductStorageTests.md
    - ProductShipmentTests: tests/ProductShipmentTests.md
    - ProductReviewTests: tests/ProductReviewTests.md
    - ProductPropertyTests: tests/ProductPropertyTests.md
    - ProductPriceTests: tests/ProductPriceTests.md
    - ProductPaymentTests: tests/ProductPaymentTests.md
    - ProductOptionTests: tests/ProductOptionTests.md
    - ProductFavouriteTests: tests/ProductFavouriteTests.md
    - ProductEnGbTests: tests/ProductEnGbTests.md
    - ProductCategoryTests: tests/ProductCategoryTests.md
    - ProductAttributeTests: tests/ProductAttributeTests.md
    - ProductAttachmentTests: tests/ProductAttachmentTests.md
    - ProductTests: tests/ProductTests.md
    - PaymentTokenTests: tests/PaymentTokenTests.md
    - PaymentMethodTests: tests/PaymentMethodTests.md
    - PaymentGatewayTests: tests/PaymentGatewayTests.md
    - PaymentEnUsTests: tests/PaymentEnUsTests.md
    - PaymentTests: tests/PaymentTests.md
    - OrderStorageTests: tests/OrderStorageTests.md
    - OrderStatusHistoryTests: tests/OrderStatusHistoryTests.md
    - OrderStatusTests: tests/OrderStatusTests.md
    - OrderShipmentEnUsTests: tests/OrderShipmentEnUsTests.md
    - OrderShipmentTests: tests/OrderShipmentTests.md
    - OrderPaymentEnUsTests: tests/OrderPaymentEnUsTests.md
    - OrderPaymentTests: tests/OrderPaymentTests.md
    - OrderLogTests: tests/OrderLogTests.md
    - OrderItemTests: tests/OrderItemTests.md
    - OrderDiscountTests: tests/OrderDiscountTests.md
    - OrderBillingTests: tests/OrderBillingTests.md
    - OAuthTraitTests: tests/OAuthTraitTests.md
    - ModuleMenuTests: tests/ModuleMenuTests.md
    - ModuleTests: tests/ModuleTests.md
    - MetaTraitTests: tests/MetaTraitTests.md
    - MenuItemTests: tests/MenuItemTests.md
    - LocaleEnTests: tests/LocaleEnTests.md
    - LocaleTests: tests/LocaleTests.md
    - IdempotencyKeyEntityTests: tests/IdempotencyKeyEntityTests.md
    - EventMemberTests: tests/EventMemberTests.md
    - EventCategoryTests: tests/EventCategoryTests.md
    - EventTests: tests/EventTests.md
    - EntityAssociationHydratorTests: tests/EntityAssociationHydratorTests.md
    - CouponTests: tests/CouponTests.md
    - AddressZipcodeTests: tests/AddressZipcodeTests.md
    - AddressStreetLineTests: tests/AddressStreetLineTests.md
    - AddressStreetTests: tests/AddressStreetTests.md
    - AddressProvinceTests: tests/AddressProvinceTests.md
    - AddressCountryTests: tests/AddressCountryTests.md
    - AddressCodeTests: tests/AddressCodeTests.md
    - AddressCityTests: tests/AddressCityTests.md
    - AddressTests: tests/AddressTests.md
  - CI/CD:
    - CI: ci/
  - Contributing:
    - Contributing: contributing/CONTRIBUTING.md
    - Security: contributing/SECURITY.md
    - Roadmap: contributing/ROADMAP.md
  - API:
    - Overview: api/README.md
    - Insomnia: api/insomnia/
    - Postman: api/postman/
    - Doxygen: ci/doxygen.md
  - Diagrams:
    - Vendor: diagrams/vendor.md
    - Product: diagrams/product.md
    - Order: diagrams/order.md
    - Payment: diagrams/payment.md
    - Address: diagrams/address.md
    - Locale: diagrams/locale.md
    - Event: diagrams/event.md
    - Role: diagrams/role.md
    - Module: diagrams/module.md
    - Coupon: diagrams/coupon.md
    - Zone: diagrams/zone.md
    - Overview: diagrams/overview.md
    - API Routes Overview: diagrams/api_overview.md
