prometheus:
  retention: 3d
  replicas: 1
grafana:
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: false
pushgateway:
  replicas: 1
ingress:
  enabled: true
  host: monitor.staging.local
