doctrine:
    dbal:
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
        default_connection: postgres
        connections:
            postgres:
                url: '%env(PLATFORM_DATA_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '11.2'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                schema_filter: '~^(?!messenger_messages)~'
            review:
                url: '%env(resolve:OBJECT_REVIEW_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '11.2'
                charset: utf8
            sqlite:
                url: '%env(resolve:PLATFORM_SYSTEM_DATABASE)%'
                driver: 'pdo_sqlite'
                server_version: '3.21'
                charset: utf8mb4

    orm:
        resolve_target_entities:
            App\Interface\CategoryInterface: App\Entity\Category\Category
            App\Interface\CategoryAttachmentInterface: App\Entity\Category\CategoryAttachment
            App\Interface\ProjectInterface: App\Entity\Project\Project
            App\Interface\ProjectTypeInterface: App\Entity\Project\ProjectType
            App\Interface\ProductTypeInterface: App\Entity\Product\ProductType
            App\Interface\FeaturedInterface: App\Entity\Featured\Featured
            App\Interface\ProductReviewInterface: App\Entity\Review\Review
            App\Interface\ProjectReviewInterface: App\Entity\Review\Review

        default_entity_manager: postgres
        entity_managers:
            postgres:
                connection: postgres
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    Product:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Product'
                        prefix: 'App\Entity\Product'
                        alias: Product
                    Project:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: Project
                    Vendor:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Vendor'
                        prefix: 'App\Entity\Vendor'
                        alias: Vendor
                    Order:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Order'
                        prefix: 'App\Entity\Order'
                        alias: Order
                    Commission:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Commission'
                        prefix: 'App\Entity\Commission'
                        alias: Commission
                    Payment:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Payment'
                        prefix: 'App\Entity\Payment'
                        alias: Payment
                    Shipment:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Shipment'
                        prefix: 'App\Entity\Shipment'
                        alias: Shipment
                    Storage:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Storage'
                        prefix: 'App\Entity\Storage'
                        alias: Storage
                    Taxation:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Taxation'
                        prefix: 'App\Entity\Taxation'
                        alias: Taxation
                    User:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/User'
                        prefix: 'App\Entity\User'
                        alias: User
                    Security:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Security'
                        prefix: 'App\Entity\Security'
                        alias: Security
                    Message:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Message'
                        prefix: 'App\Entity\Message'
                        alias: Message
                    Event:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Event'
                        prefix: 'App\Entity\Event'
                        alias: Event
                    Featured:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Featured'
                        prefix: 'App\Entity\Featured'
                        alias: Featured

            review:
                connection: review
                mappings:
                    Review:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Review'
                        prefix: 'App\Entity\Review'
                        alias: Review

            sqlite:
                connection: sqlite
                mappings:
                    Module:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Module'
                        prefix: 'App\Entity\Module'
                        alias: Module
                    Category:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Category'
                        prefix: 'App\Entity\Category'
                        alias: Category
                    ProjectType:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: ProjectType
                    ProductType:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Product'
                        prefix: 'App\Entity\Product'
                        alias: ProductType

        auto_generate_proxy_classes: true

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
