services:
  # Doctrine subscribers
  App\EventListener\GroupedFixtureExecutorListener: ~
  App\EventListener\RepositoryMetadataManagerListener: ~
  # Kernel subscribers
  App\EventListener\CartSessionSubscriber: ~
  App\EventListener\ReviewListener: ~
  App\EventListener\SitemapListener: ~
  App\EventListener\UpdateUserEncoderListener: ~
  App\EventListener\ShopUserLogoutHandler: ~
