image:
  repository: ghcr.io/acme/order
  tagStable: "v1.0.0"
  tagCanary: "v1.1.0"
  pullPolicy: IfNotPresent

replicaCount:
  stable: 2
  canary: 1

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: order.smartresponsor.local
  canaryWeight: 10
  annotations: {}
  tls:
    enabled: false
    secretName: ""

resources: {}
