{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata: { name: {{ .Values.secrets.name }} }
type: Opaque
stringData:
  JWT_PASSPHRASE: "{{ .Values.secrets.data.JWT_PASSPHRASE }}"
---
apiVersion: v1
kind: Secret
metadata: { name: ordercomponent-jwt }
type: Opaque
stringData:
  private.pem: |-
{{ .Values.secrets.files.privatePem | indent 4 }}
  public.pem: |-
{{ .Values.secrets.files.publicPem | indent 4 }}
{{- end }}
