apiVersion: v1
kind: Service
metadata: { name: ordercomponent-svc }
spec:
  type: {{ .Values.service.type }}
  selector: { app: ordercomponent-app }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
