services:
  App\EventSubscriber\DoctrineEventSubscriber:
    tags: ['doctrine.event_subscriber']

  App\Service\FileStorageService:
    arguments:
      $defaultStorage: '@flysystem.local'
      $s3Storage: '@flysystem.s3'
      $logger: '@logger'

  aws.s3:
    class: AsyncAws\S3\S3Client
    arguments:
      -
        region: '%env(AWS_REGION)%'
        accessKeyId: '%env(AWS_ACCESS_KEY_ID)%'
        accessKeySecret: '%env(AWS_SECRET_ACCESS_KEY)%'
        endpoint: '%env(resolve:AWS_ENDPOINT)%'
